name: Release binary

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: ["386", amd64]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Setup go and release
        uses: wangyoucao577/go-release-action@v1.49
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
